import Head from 'next/head'
import { Footer, Header } from '../organism'

type Props = {
  children: React.ReactNode
}

const LayoutAtype:React.FC<Props> = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <div>
        
        {children}
      </div>
      <Footer />
    </>
  )
}

export default LayoutAtype;