import Head from "next/head";
import { Footer, Header, SideBar, StatusBar } from "../organism";
import classNames from "classnames/bind";
import style from "./layoutA.module.scss";
const cx = classNames.bind(style);

type Props = {
  children: React.ReactNode;
};

const LayoutAtype: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={cx(`layout__type--a`)}>
        <Header />
        <SideBar />
        <div className={cx(`content`)}>
          <StatusBar />
          {children}
        </div>
        <Footer />
      </div>
    </>
  );
};

export default LayoutAtype;
